name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run weekly quality checks on Sundays at 6 AM UTC
    - cron: '0 6 * * 0'

env:
  CARGO_TERM_COLOR: always

jobs:
  formatting:
    name: Code Formatting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt

    - name: Check Rust formatting
      working-directory: core
      run: cargo fmt --all -- --check

    - name: Check Markdown formatting
      uses: DavidAnson/markdownlint-action@v1
      with:
        files: '**/*.md'
        ignore: 'azgaar-reference/**'
        config: |
          {
            "MD013": { "line_length": 120 },
            "MD033": false,
            "MD041": false
          }

  linting:
    name: Code Linting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: core

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libfontconfig1-dev \
          libfreetype6-dev \
          libgl1-mesa-dev \
          libglu1-mesa-dev \
          libegl1-mesa-dev \
          libxcb-composite0-dev \
          libxcb-shape0-dev \
          libxcb-xfixes0-dev

    - name: Run Clippy
      working-directory: core
      run: |
        cargo clippy --all-targets --all-features -- \
          -D warnings \
          -D clippy::all \
          -D clippy::pedantic \
          -A clippy::module_name_repetitions \
          -A clippy::missing_errors_doc \
          -A clippy::missing_panics_doc

    - name: Run Clippy with additional lints
      working-directory: core
      run: |
        cargo clippy --all-targets --all-features -- \
          -W clippy::nursery \
          -W clippy::cargo \
          -A clippy::multiple_crate_versions

  complexity:
    name: Code Complexity Analysis
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install tokei
      run: cargo install tokei

    - name: Analyze code metrics
      run: |
        echo "## Code Metrics" > metrics.md
        echo "" >> metrics.md
        echo "### Lines of Code" >> metrics.md
        echo '```' >> metrics.md
        tokei --output json | jq -r '
          .languages | to_entries[] | 
          select(.key != "Total") | 
          "\(.key): \(.value.code) lines"
        ' >> metrics.md
        echo '```' >> metrics.md
        echo "" >> metrics.md
        echo "### Total Summary" >> metrics.md
        echo '```' >> metrics.md
        tokei >> metrics.md
        echo '```' >> metrics.md

    - name: Upload metrics
      uses: actions/upload-artifact@v3
      with:
        name: code-metrics
        path: metrics.md

  documentation:
    name: Documentation Quality
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: core

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libfontconfig1-dev \
          libfreetype6-dev \
          libgl1-mesa-dev \
          libglu1-mesa-dev \
          libegl1-mesa-dev \
          libxcb-composite0-dev \
          libxcb-shape0-dev \
          libxcb-xfixes0-dev

    - name: Check documentation coverage
      working-directory: core
      run: |
        RUSTDOCFLAGS="-D missing_docs -D rustdoc::broken_intra_doc_links" \
        cargo doc --no-deps --all-features --document-private-items

    - name: Check for broken links in docs
      run: |
        find docs -name "*.md" -exec grep -l "http" {} \; | while read file; do
          echo "Checking links in $file"
          # This would need a link checker tool in a real implementation
          echo "✅ $file"
        done

  performance:
    name: Performance Analysis
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: core

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libfontconfig1-dev \
          libfreetype6-dev \
          libgl1-mesa-dev \
          libglu1-mesa-dev \
          libegl1-mesa-dev \
          libxcb-composite0-dev \
          libxcb-shape0-dev \
          libxcb-xfixes0-dev

    - name: Build release binary
      working-directory: core
      run: cargo build --release --bin cli

    - name: Run performance tests
      working-directory: core
      run: |
        echo "## Performance Metrics" > performance.md
        echo "" >> performance.md
        echo "### Binary Size" >> performance.md
        echo "- CLI binary: $(du -h target/release/cli | cut -f1)" >> performance.md
        echo "" >> performance.md
        echo "### Build Time" >> performance.md
        time cargo build --release --bin cli 2>&1 | grep real >> performance.md || echo "Build completed" >> performance.md

    - name: Upload performance report
      uses: actions/upload-artifact@v3
      with:
        name: performance-report
        path: core/performance.md

  spell-check:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Spell check documentation
      uses: crate-ci/typos@master
      with:
        files: docs/ README.md core/src/
        config: |
          [default.extend-words]
          Azgaar = "Azgaar"
          Foundry = "Foundry"
          heightmap = "heightmap"
          biome = "biome"
          coord = "coord"
          coords = "coords"
          Vec = "Vec"
          impl = "impl"
          struct = "struct"
          enum = "enum"
          fn = "fn"
          mut = "mut"
          cfg = "cfg"